### ISSUE TITLE
a "\n" is missing between CanonicalizedHeaders and CanonicalizedResource in Authentication of Signature in a Header

### ISSUE THREAD

**Issue by j-schwoebel-zbw** [opentelekomcloud-docs/object-storage-service#91] opened 2024-03-27 17:10 UTC
Issue on page:        https://github.com/opentelekomcloud-docs/object-storage-service/blob/main/api-ref/source/calling_apis/authentication/authentication_of_signature_in_a_header.rst

For my use case, a "\n" is missing between CanonicalizedHeaders and CanonicalizedResource.

I need this additional \n when using _both_ CanonicalizedHeader and CanonicalizedResource:
signature_string="PUT\n\n${contentType}\n${dateValue}\nx-obs-bucket-object-lock-enabled:true\n${filepath}"
(For a full code example, take a look at the comments in https://community.open-telekom-cloud.com/community?id=community_blog&sys_id=080bfe8813c671d8d15a246ea674416e)

Please note that the additional "\n" which i am suggesting seems not to be always mandatory, unlike the other "\n"s in StringToSign. In the example section, it is always omitted. None of the example uses both CanonicalizedHeaders and CanonicalizedResource, though.
Also note that the (imo) partially incorrect Stringtosign-pattern can be found on neighbouring doc pages as well, such as https://docs.otc.t-systems.com/object-storage-service/api-ref/calling_apis/authentication/user_signature_authentication.html

**Comment by dsabelni** [comment] 2024-03-28 11:34
Hello @j-schwoebel-zbw !

Just to make sure - in order for it to work did you need to put two new lines between CanonicalizedHeaders and CanonicalizedResource like:
```
header1\n
header2\n
\n
resource
```
Or was it like:
```
header1\n
header2\n
resource
```
? The way it should work is the second one with only one new line between CanonicalizedHeaders and CanonicalizedResource - it is confirmed in some of the examples, e.g. in the **Table 4 An object upload request containing header fields** (there _x-obs-acl:public-read_ is the CanonicalizedHeaders and _/bucket/object.txt_ is the CanonicalizedResource parts - and between them one new line '\n' is located).

In any case I agree that StringToSign description
```
StringToSign =
    HTTP-Verb + "\n" +
    Content-MD5 + "\n" +
    Content-Type + "\n" +
    Date + "\n" +
    CanonicalizedHeaders + CanonicalizedResource
```
should be updated to:
```
StringToSign =
    HTTP-Verb + "\n" +
    Content-MD5 + "\n" +
    Content-Type + "\n" +
    Date + "\n" +
    CanonicalizedHeaders + "\n" +
    CanonicalizedResource
```

**Comment by j-schwoebel-zbw** [comment] 2024-03-28 12:36
Hi dsabelni,

thanks for pointing out Table 4, I overlooked that. Sorry for that! As far as i understand, my example is not any different from the pattern in Table 4.

My code resembles your latter example. i did
signature_string="HTTP-Verb\n\nContent-MD5\nDate\nx-obs-bucket-object-lock-enabled:true\nCanonicalizedResource"
so no double \n\n preceding resource.


I haven't had a good idea on how to update the docs properly.
Your proposition

StringToSign =
    HTTP-Verb + "\n" +
    Content-MD5 + "\n" +
    Content-Type + "\n" +
    Date + "\n" +
    CanonicalizedHeaders + "\n" +
    CanonicalizedResource

might mislead people to _always_ add the additional \n, even if not using _both_ CanonicalHeaders and CanonicalResource. Looking at the other examples, it looks like this \n should be omitted when only using either CanonicalHeaders or CanonicalResource. In contrast, the other "\n"s above seem to be mandatory, compare Table 2.

I haven't found a good way to put this into the existing lines. My best effort:

StringToSign =
    HTTP-Verb + "\n" +
    Content-MD5 + "\n" +
    Content-Type + "\n" +
    Date + "\n" +
    CanonicalizedHeaders + "\n" +        ...only add this "\n" if using BOTH CanonicalizedHeaders and CanonicalizedResource
    CanonicalizedResource

this suggestion contains the information but looks ugly.

Looking at the examples again i'm a bit confused now because in examples Table 2,4,5 , three "\n"s precede the date, while it's four "\n"s in Table 3,6,7. Obviously, i haven't fully understood the syntax here, so my suggestions might be incorrect. Just to re-iterate, i needed an extra \n in my use case, that was my main concern.

**Comment by dsabelni** [comment] 2024-03-28 15:48
I agree, my proposition wouldn't work for situations when there is only CanonicalizedHeaders or CanonicalizedResource present. Another suggestion could be leaving the StringToSign description part as it currently is but adding Note to the _CanonicalizedResource_ description in the **Table 1 Parameters required for constructing a StringToSign** saying something like:
"Should be located on a separate line from CanonicalizedHeaders"

About examples in Tables 3,6,7 - it seems to me the reason is that the date is presented not in a usual "date" header but in a canonicalized header "x-obs-date", so that's why the date goes to the CanonicalizedHeaders part and the Date part of StringToSign stays as an empty line. But the problem is that I don't think this "x-obs-date" header is documented anywhere in the OBS documentation (at least I don't see it in the PUT Object page, and the examples are for the PUT Object operation), so it's probably better to update examples so they have a regular "date" header instead.

**Comment by dsabelni** [comment] 2024-05-02 07:52
Testing of the "x-obs-date" header has shown that it works the same way it is described in the pages so the update should only include a Note to the CanonicalizedResource description in the Table 1 Parameters required for constructing a StringToSign :
"Should be located on a separate line from CanonicalizedHeaders"

**Comment by dsabelni** [comment] 2024-05-02 15:23
Information is added to the pages:

- https://docs.otc.t-systems.com/object-storage-service/api-ref/calling_apis/authentication/authentication_of_signature_in_a_header.html
- https://docs.otc.t-systems.com/object-storage-service/api-ref/calling_apis/authentication/authentication_of_signature_in_a_url.html

to the note for CanonicalizedResource in Parameters required for constructing a StringToSign tables:

> CanonicalizedResource should be located on a separate line from CanonicalizedHeaders.

I'm closing the issue.

**Closed by dsabelni** 2024-05-02 15:23 UTC
